'use client'
import { getProtected } from '@/requests/get'
import Head from 'next/head'
import { useRouter } from 'next/navigation'
import { useEffect } from 'react'
import styles from './page.module.css'

export default function Home() {
  useEffect(() => {
    getCurrentAuthState()
  }, [])

  const router = useRouter()

  const getCurrentAuthState = async () => {
    try {
      const currentAuthState = await getProtected("auth/current-auth-state")

      console.log("Getting current auth state");


      console.log({ theCurrentAuthState: currentAuthState });


      if (!currentAuthState || currentAuthState.status === "Failed") {
        router.push("/login")
      } else if (currentAuthState.data.role === "Vendor") {
        router.push("/contractor/dashboard")


      } else if (currentAuthState.data.role !== "Vendor") {


        router.push("/staff/approvals")

        localStorage.setItem("role", "Staff")
        localStorage.setItem("user", JSON.stringify(currentAuthState.data))
      } else {
        router.push("/login");
      }



    } catch (error) {
      console.log({ error });
    }
  }

  return (
    <main className={styles.main}>

      <Head>
        <title>Amni Contractors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>

    </main>
  )
}
