'use client'
import Head from 'next/head'
import { useRouter } from 'next/navigation'
import { useEffect } from 'react'
import styles from './page.module.css'

export default function Home() {

  const router = useRouter();

  useEffect(() => {
    router.push('/login');
  }, [])

  return (
    <main className={styles.main}>

      <Head>
        <title>Amni Contractors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>

    </main>
  )
}
